name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: bad-bank-bjvd #Must be unique in Heroku
          heroku_email: bjvong@gmail.com
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - uses: jakejarvis/s3-sync-action@master
  #     with:
  #       args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
  #     env:
  #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}